services:
  api:
    image: "node:${VERSION_NODE}"
    command: "yarn start:dev"
    user: node
    working_dir: /home/node/nest
    environment:
      - PUERTO_NESTJS=${PUERTO_NEST}
    ports:
      - "5000:${PUERTO_NEST}"
    volumes:
      - .:/home/node/nest
  db:
    image: "mysql:${VERSION_DB}"
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "5001:3306"